image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"


cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python --version
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r Server/requirements.txt

stages:
    - test
    - style

pytest:
    stage: test
    script:
        - pytest Server/pytests.py 


codeStyle:
    stage: style
    script:
        - pylint --disable=C0412,W0702 Server/socket_server.py
        - pylint --disable=C0412 Server/fast_api_server.py